### ISSUE TITLE
Failed resolution of: Landroid/support/v7/app/NotificationCompat$Builder;

### ISSUE THREAD

**Issue by wallyperry** [wenmingvs/NotifyUtil#14]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/NotificationCompat$Builder;
        at com.wenming.library.NotifyUtil.<init>(NotifyUtil.java:38)
        at ren.perry.tadpole.receiver.MQReceiver.onReceive(MQReceiver.java:33)
        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.NotificationCompat$Builder" on path: DexPathList[[zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/base.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_dependencies_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_resources_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_0_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_1_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_2_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_3_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_4_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_5_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_6_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_7_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_8_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/base.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_dependencies_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_resources_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_0_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_1_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_2_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_3_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_4_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_5_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_6_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_7_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_8_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_9_apk.apk!/lib/x86_64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.wenming.library.NotifyUtil.<init>(NotifyUtil.java:38) 
        at ren.perry.tadpole.receiver.MQReceiver.onReceive(MQReceiver.java:33) 
        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313) 
        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)

**Comment by Xheng4** [comment]
> java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/NotificationCompat$Builder;
> at com.wenming.library.NotifyUtil.(NotifyUtil.java:38)
> at ren.perry.tadpole.receiver.MQReceiver.onReceive(MQReceiver.java:33)
> at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
> at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loop(Looper.java:193)
> at android.app.ActivityThread.main(ActivityThread.java:6669)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.NotificationCompat$Builder" on path: DexPathList[[zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/base.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_dependencies_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_resources_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_0_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_1_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_2_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_3_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_4_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_5_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_6_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_7_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_8_apk.apk", zip file "/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/base.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_dependencies_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_resources_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_0_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_1_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_2_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_3_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_4_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_5_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_6_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_7_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_8_apk.apk!/lib/x86_64, /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_slice_9_apk.apk!/lib/x86_64, /system/lib64]]
> at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> at com.wenming.library.NotifyUtil.(NotifyUtil.java:38) 
> at ren.perry.tadpole.receiver.MQReceiver.onReceive(MQReceiver.java:33) 
> at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313) 
> at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121) 
> at android.os.Handler.dispatchMessage(Handler.java:106) 
> at android.os.Looper.loop(Looper.java:193) 
> at android.app.ActivityThread.main(ActivityThread.java:6669) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
> Suppressed: java.io.IOException: No original dex files found for dex location /data/app/ren.perry.tadpole-xRyTgOBhJaLBNuiUe4TmcQ==/split_lib_resources_apk.apk
> at dalvik.system.DexFile.openDexFileNative(Native Method)
> at dalvik.system.DexFile.openDexFile(DexFile.java:354)
> at dalvik.system.DexFile.(DexFile.java:101)

v7换成v4
